from __future__ import annotations

import argparse
from pathlib import Path

from ncls.learning.models.metal_budgeted_profile import (
    METAL_BUDGETED_LAYOUT_PATH,
    load_metal_budgeted_layout,
)
from ncls.paths import PROJECT_ROOT


DEFAULT_OUTPUT = (
    PROJECT_ROOT
    / "shaders/ncls/backends/metal_budgeted/metal_budgeted_layout.generated.slang"
)


def _constant_name(value: str) -> str:
    return value.upper().replace("-", "_")


def render() -> str:
    layout = load_metal_budgeted_layout(METAL_BUDGETED_LAYOUT_PATH)
    shape = layout["shape"]
    bounded = layout["bounded_execution"]
    proposal = layout["proposal"]
    state = layout["prepared_state"]
    offsets = "\n".join(
        f"static const uint NCLS_METAL_BUDGETED_PREPARED_{_constant_name(str(field['name']))}_OFFSET = {int(field['offset'])}u;"
        for field in state["fields"]
    )
    components = "\n".join(
        f"// {index}: {name}" for index, name in enumerate(proposal["components"])
    )
    return f"""#ifndef NCLS_METAL_BUDGETED_LAYOUT_GENERATED_SLANG
#define NCLS_METAL_BUDGETED_LAYOUT_GENERATED_SLANG

// Generated by tools/learning/generate_metal_budgeted_layout.py.
// Source layout identity: {layout['identity']}
static const uint NCLS_METAL_BUDGETED_TEXTURE_READS = {int(bounded['maximum_texture_reads'])}u;
static const uint NCLS_METAL_BUDGETED_PREPARED_STATE_BYTES = {int(state['total_bytes'])}u;
static const uint NCLS_METAL_BUDGETED_EVALUATE_DENSE_MACS = {int(shape['evaluate_dense_macs'])}u;
static const uint NCLS_METAL_BUDGETED_DIRECTION_WIDTH = {int(shape['directional_width'])}u;
static const uint NCLS_METAL_BUDGETED_PROPOSAL_COMPONENT_COUNT = {int(shape['proposal_component_count'])}u;
static const float NCLS_METAL_BUDGETED_FALLBACK_WEIGHT_FLOOR = {float(proposal['fallback_weight_floor']):.9g}f;

{offsets}

{components}

#endif
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="生成 Metal budgeted Slang layout 常量")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    content = render()
    output = arguments.output.resolve()
    if arguments.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != content:
            raise SystemExit("Metal budgeted generated layout is stale")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8", newline="\n")
    print(output.relative_to(PROJECT_ROOT).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
