from __future__ import annotations

import argparse
from pathlib import Path

from ncls.learning.models.metal_fused_profile import (
    METAL_FUSED_LAYOUT_PATH,
    load_metal_fused_layout,
)
from ncls.paths import PROJECT_ROOT


DEFAULT_OUTPUT = (
    PROJECT_ROOT
    / "shaders/ncls/backends/metal_fused/metal_fused_layout.generated.slang"
)


def _switch(name: str, values: list[int], return_type: str = "uint") -> str:
    cases = "\n".join(
        f"        case {index}u: return {str(value).lower() if return_type == 'bool' else f'{value}u'};"
        for index, value in enumerate(values)
    )
    fallback = "false" if return_type == "bool" else "0u"
    return f"""{return_type} {name}(uint component)
{{
    switch (component)
    {{
{cases}
        default: return {fallback};
    }}
}}"""


def render() -> str:
    layout = load_metal_fused_layout(METAL_FUSED_LAYOUT_PATH)
    proposal = layout["proposal_reservation"]
    fields = {name: index for index, name in enumerate(proposal["state_fields"])}
    required_fields = {
        "normalized_weight",
        "alpha_x",
        "alpha_y",
        "rotation_radians",
        "active",
        "frame_index",
        "distribution_id",
        "energy_clue",
    }
    if set(fields) != required_fields or len(fields) != 8:
        raise ValueError("Metal proposal state fields drifted from the frozen width")
    components = list(proposal["components"])
    frame_indices = [int(value) for value in proposal["component_frame_indices"]]
    distribution_ids = [
        int(value) for value in proposal["component_distribution_ids"]
    ]
    specular = [bool(value) for value in proposal["component_specular_flags"]]
    if not (
        len(components)
        == len(frame_indices)
        == len(distribution_ids)
        == len(specular)
        == 11
    ):
        raise ValueError("Metal proposal component tables must all have length 11")
    enums = proposal["distribution_enum"]
    component_comments = "\n".join(
        f"// {index}: {name}" for index, name in enumerate(components)
    )
    field_constants = "\n".join(
        f"static const uint NCLS_METAL_PROPOSAL_FIELD_{name.upper()} = {index}u;"
        for name, index in fields.items()
    )
    return f"""#ifndef NCLS_METAL_FUSED_LAYOUT_GENERATED_SLANG
#define NCLS_METAL_FUSED_LAYOUT_GENERATED_SLANG

// Generated by tools/learning/generate_metal_sampler_layout.py.
// Source layout identity: {layout['identity']}
static const uint NCLS_METAL_PROPOSAL_COMPONENT_COUNT = {len(components)}u;
static const uint NCLS_METAL_PROPOSAL_STATE_WIDTH = {len(fields)}u;
static const uint NCLS_METAL_PROPOSAL_FRAME_COUNT = 4u;
static const float NCLS_METAL_PROPOSAL_FALLBACK_WEIGHT_FLOOR = {float(proposal['fallback_weight_floor']):.9g}f;
static const uint NCLS_METAL_DISTRIBUTION_GGX = {int(enums['folded-anisotropic-ggx'])}u;
static const uint NCLS_METAL_DISTRIBUTION_BECKMANN = {int(enums['folded-anisotropic-beckmann'])}u;
static const uint NCLS_METAL_DISTRIBUTION_COSINE = {int(enums['folded-cosine'])}u;
static const uint NCLS_METAL_DISTRIBUTION_UNIFORM = {int(enums['folded-uniform'])}u;

{field_constants}

{component_comments}

{_switch('nclsMetalProposalFrameIndex', frame_indices)}

{_switch('nclsMetalProposalDistribution', distribution_ids)}

{_switch('nclsMetalProposalIsSpecular', [str(value).lower() for value in specular], 'bool')}

#endif
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="生成Metal matched sampler Slang ABI")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    content = render()
    output = arguments.output.resolve()
    if arguments.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != content:
            raise SystemExit("Metal generated sampler layout is stale")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8", newline="\n")
    print(output.relative_to(PROJECT_ROOT).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
