"""MaterialProgram、规范化 LayerStackIR 和 ABI。"""

from .canonical import (
    canonical_material_json,
    canonicalize_layer_stack,
    material_program_from_layer_stack,
    physical_material_hash,
    validate_material_program,
)
from .layer_stack import (
    ABI_MAGIC,
    ABI_VERSION,
    BINARY_SIZE,
    MAX_INTERFACES,
    MAX_MEDIA,
    DiffuseInterface,
    HomogeneousMedium,
    InterfaceKind,
    LayerInterfaceIR,
    LayerStackIR,
    RoughConductorInterface,
    RoughDielectricInterface,
    SheenInterface,
    pack_layer_stack,
    pack_layer_interface,
    unpack_layer_stack,
    unpack_layer_interface,
)
from .program import (
    MATERIAL_PROGRAM_SCHEMA,
    MATERIAL_PROGRAM_VERSION,
    MaterialNode,
    MaterialProgram,
    MaterialResource,
    NodeConnection,
    OperationId,
    ParameterSource,
    ValueType,
)

__all__ = [
    "ABI_MAGIC",
    "ABI_VERSION",
    "BINARY_SIZE",
    "MATERIAL_PROGRAM_SCHEMA",
    "MATERIAL_PROGRAM_VERSION",
    "MAX_INTERFACES",
    "MAX_MEDIA",
    "DiffuseInterface",
    "HomogeneousMedium",
    "InterfaceKind",
    "LayerInterfaceIR",
    "LayerStackIR",
    "MaterialNode",
    "MaterialProgram",
    "MaterialResource",
    "NodeConnection",
    "OperationId",
    "ParameterSource",
    "RoughConductorInterface",
    "RoughDielectricInterface",
    "SheenInterface",
    "ValueType",
    "canonical_material_json",
    "canonicalize_layer_stack",
    "material_program_from_layer_stack",
    "pack_layer_stack",
    "pack_layer_interface",
    "physical_material_hash",
    "unpack_layer_stack",
    "unpack_layer_interface",
    "validate_material_program",
]
